/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signify;

import Algo.Signify_LSB;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jay
 */
public class MainActivity extends javax.swing.JFrame {

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        secretMsgTxtArea = new javax.swing.JTextArea();
        browesImgBtn = new javax.swing.JButton();
        ImgPath = new javax.swing.JLabel();
        maxDataLabel = new javax.swing.JLabel();
        hideDataBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        browesImgBtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        secretDataTxtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        warningMsg1 = new javax.swing.JLabel();
        retrieveDataBtn = new javax.swing.JButton();
        dataRetreivePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        secretMsgTxtArea.setColumns(20);
        secretMsgTxtArea.setRows(5);
        secretMsgTxtArea.setText("write your secret message here...");
        jScrollPane1.setViewportView(secretMsgTxtArea);

        browesImgBtn.setText("Browes Image");
        browesImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesImgBtnActionPerformed(evt);
            }
        });

        ImgPath.setText(" ");

        maxDataLabel.setText("Max Data : ");

        hideDataBtn.setText("Hide Data");
        hideDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideDataBtnActionPerformed(evt);
            }
        });

        warningLabel.setForeground(new java.awt.Color(234, 33, 33));
        warningLabel.setText(" ");

        jButton1.setText("Browse File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImgPath)
                    .addComponent(warningLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browesImgBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hideDataBtn)
                                .addComponent(maxDataLabel)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browesImgBtn)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImgPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDataLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hideDataBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Hide Data", jPanel1);

        browesImgBtn1.setText("Browes Image");
        browesImgBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesImgBtn1ActionPerformed(evt);
            }
        });

        secretDataTxtArea.setColumns(20);
        secretDataTxtArea.setRows(5);
        jScrollPane2.setViewportView(secretDataTxtArea);

        jLabel1.setText("Secret Data");

        warningMsg1.setForeground(new java.awt.Color(194, 16, 16));
        warningMsg1.setText(" ");

        retrieveDataBtn.setText("Retrieve Data");
        retrieveDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browesImgBtn1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(retrieveDataBtn)
                    .addComponent(dataRetreivePath)
                    .addComponent(warningMsg1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browesImgBtn1)
                .addGap(4, 4, 4)
                .addComponent(dataRetreivePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retrieveDataBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningMsg1)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Retrive Data", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browesImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesImgBtnActionPerformed
        
        this.warningLabel.setText(" ");
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.ImgPath.setText(path);
                try {
                    BufferedImage imgFile = ImageIO.read(new File(path));
                    System.out.println((long)Signify_LSB.getMaxStorableData(imgFile));
                    String msg="Max Data:"+ String.valueOf((long)Signify_LSB.getMaxStorableData(imgFile)/(8.0*1024))+"kB" ;//bits/8=bytes
                    this.maxDataLabel.setText(msg);
                } catch (IOException ex) {
                    Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

    }//GEN-LAST:event_browesImgBtnActionPerformed

    private void hideDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideDataBtnActionPerformed
        
        String secretMsg = this.secretMsgTxtArea.getText();
        BufferedImage imgFile;
        try {
            imgFile = ImageIO.read(new File(this.ImgPath.getText()));
            System.out.println(secretMsg.length()+" " +(Signify_LSB.getMaxStorableData(imgFile)/8));
            /*if(secretMsg.length()*8>(Signify_LSB.getMaxStorableData(imgFile)))
            {
                this.warningLabel.setText("Either choose bigger File or shorten your message");
                return;
            }*/
            if(new File(this.jLabel2.getText()).length()*8>(Signify_LSB.getMaxStorableData(imgFile)))
            {
                this.warningLabel.setText("Either choose bigger File or shorten your message");
                return;
            }
        } catch (IOException ex) {
            this.warningLabel.setText("Choose Image File First");
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            //Signify_LSB.hideData(secretMsg,this.ImgPath.getText());
            Signify_LSB.hideData(this.jLabel2.getText(), this.ImgPath.getText());
        } catch (IOException ex) {
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.secretMsgTxtArea.setText("write your secret message here...");
        
    }//GEN-LAST:event_hideDataBtnActionPerformed

    private void browesImgBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesImgBtn1ActionPerformed
        
        this.secretDataTxtArea.setText("");
        this.warningMsg1.setText(" ");
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.dataRetreivePath.setText(path);
            }
    }//GEN-LAST:event_browesImgBtn1ActionPerformed

    private void retrieveDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveDataBtnActionPerformed
       
        try {
            //String secret= Signify_LSB.retrieveData(this.dataRetreivePath.getText());
            String secret=Signify_LSB.retrieveData(this.dataRetreivePath.getText());
            System.out.println(secret);
            this.secretDataTxtArea.setText(secret);
        } catch (IOException ex) {
            this.warningMsg1.setText("Choose Image File First");
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retrieveDataBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        //fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.jLabel2.setText(path);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgPath;
    private javax.swing.JButton browesImgBtn;
    private javax.swing.JButton browesImgBtn1;
    private javax.swing.JLabel dataRetreivePath;
    private javax.swing.JButton hideDataBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel maxDataLabel;
    private javax.swing.JButton retrieveDataBtn;
    private javax.swing.JTextArea secretDataTxtArea;
    private javax.swing.JTextArea secretMsgTxtArea;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningMsg1;
    // End of variables declaration//GEN-END:variables
}
