/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signify;

import Algo.ImageLoad;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jay
 */
public class MainActivity extends javax.swing.JFrame {

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        secretMsgTxtArea = new javax.swing.JTextArea();
        browesImgBtn = new javax.swing.JButton();
        hideDataBtn = new javax.swing.JButton();
        ImgPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        secretMsgTxtArea.setColumns(20);
        secretMsgTxtArea.setRows(5);
        secretMsgTxtArea.setText("write your secret message here...");
        jScrollPane1.setViewportView(secretMsgTxtArea);

        browesImgBtn.setText("Browes Image");
        browesImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesImgBtnActionPerformed(evt);
            }
        });

        hideDataBtn.setText("Hide Data");
        hideDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browesImgBtn)
                    .addComponent(hideDataBtn)
                    .addComponent(ImgPath))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(browesImgBtn)
                .addGap(18, 18, 18)
                .addComponent(ImgPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(hideDataBtn)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browesImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesImgBtnActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
                int returnValue = fileChooser.showOpenDialog(null);
                if (returnValue == JFileChooser.APPROVE_OPTION) 
                {
                    File selectedFile = fileChooser.getSelectedFile();
                    String path= selectedFile.getPath();
                    this.ImgPath.setText(path);
                }
        
    }//GEN-LAST:event_browesImgBtnActionPerformed

    private void hideDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideDataBtnActionPerformed
        
        String secretMsg = this.secretMsgTxtArea.getText();
        
        BufferedImage original,original1;
        try {
            original = ImageIO.read(new File(this.ImgPath.getText()));
                BufferedImage signified = new BufferedImage(original.getWidth(),original.getHeight(),BufferedImage.TYPE_INT_ARGB);

            for(int i=0;i<original.getHeight();i++)
                for(int j=0;j<original.getWidth();j++)
                    signified.setRGB(i, j,original.getRGB(i,j));

            ImageLoad.hideData(secretMsg,signified);

            original1 = ImageIO.read(new File("/home/jay/Signify/answer_Signify.png"));
                BufferedImage verified = new BufferedImage(original.getWidth(),original.getHeight(),BufferedImage.TYPE_INT_ARGB);

            for(int i=0;i<original1.getHeight();i++)
                for(int j=0;j<original1.getWidth();j++)
                    verified.setRGB(i, j,original1.getRGB(i,j));
            
            String secret= ImageLoad.retrieveData(signified);
            System.out.println("last alpha"+Integer.toBinaryString(verified.getRGB(original1.getHeight()-1, original1.getWidth()-1)) );
            System.out.println("hidden msg:"+secret);
        } catch (IOException ex) {
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_hideDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgPath;
    private javax.swing.JButton browesImgBtn;
    private javax.swing.JButton hideDataBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea secretMsgTxtArea;
    // End of variables declaration//GEN-END:variables
}
